### ISSUE TITLE
Publishing companies

### ISSUE THREAD

**Issue by sekolb** [Joachim-Raff-Archiv/portal-app#38]
Publishing companies: Under tap "Referenzen", works are listed alphabetically. After Opus No. would be better. 

https://dev.raff-archiv.ch/html/institution/D00002

**Comment by sekolb** [comment]
Same with persons: 
https://dev.raff-archiv.ch/html/person/C00114

**Comment by riedde** [comment]
This is because there is one function for all referneces in any context. I improved the function. Now the works are orderd by opus/woo and i killed the leading zeros
