### ISSUE TITLE
Pages for Schäfer/Müller-Reuter under not over scans. 

### ISSUE THREAD

**Issue by sekolb** [Joachim-Raff-Archiv/portal-app#39]
It seems to me easier to handle, especially if you have such a small screen as I do.

**Comment by riedde** [comment]
I see no need for this, hence the compromise: Above and below

**Comment by riedde** [comment]
I have to revise my last comment: It is not as easy to implement this because of the code structure. Maybe this can be done later. We should talk about this again!
