### ISSUE TITLE
Links don't work

### ISSUE THREAD

**Issue by sekolb** [Joachim-Raff-Archiv/portal-app#52]
The links in the Regesten don't work anymore. But the connection between the different entries seems to work anyway (fortuantely). 

For example: 
https://portal.raff-archiv.ch/html/letter/A00389

**Comment by riedde** [comment]
Links are disabled, if the resource can't be found. Because uf introducing sundirectories to structure the content, no resource has been found anyway, so all text markup linking was disabled. (even in fulltext view)
